%---------------------------------------------------------------------------------------------------
\chapter[Análisis demográfico]{Análisis demográfico}
\label{chp_demog}
%--------------------------------------------------------------------------------------------------

 A continuación, presentamos un análisis tabular y gráfico de las principales variables demográficas de las entidades de seguridad reguladas en el COESCOP.

\section{Estructura demográfica de las entidades reguladas en el COESCOP}

% %---------------------------------------------------------------------------------------------------
\subsection{Entidades del Sistema Especializado de Investigación, Medicina Legal y Ciencias Forenses}
\label{chp_demog:snmlcf}

%-----------------------------------------------------------------------------------------------------
Para el presente estudio se considera el número de servidores públicos del Servicio Nacional de Medicina Legal y Ciencias Forenses (SNMLCF) a marzo del 2022, que es de 182 servidores. En la figura \ref{fig:iess_pir_snmlcf} y tabla \ref{tab:iess_snmlcf_edad_sexo} se muestra la distribución por edad y sexo de las y los servidores públicos de la mencionada entidad, donde se pone en evidencia que el 44,51\% del total del personal del SNMLCF son mujeres y el 55,49\% son hombres. También, el 52,20\% del total de los empleados de esta se encuentra entre los 30 y 40 años.\\

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del SNMLCF}
\label{fig:iess_pir_snmlcf}
\includegraphics[scale=1]{graficos/iess_pir_snmlcf.png}
\caption*{\scriptsize {\bf Fuente:} Servicio Nacional de Medicina Legal y Ciencias Forenses. \\
{\bf Elaborado:} DAIE}
\end{figure}

{\fontsize{11}{13}\selectfont
\begin{longtable}[H]{crrrrrr}
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del SNMLCF}
\label{tab:iess_snmlcf_edad_sexo} \\
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\endfirsthead
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\endhead
\hline
\multicolumn{4}{r}{continúa...} \\
\endfoot
%\bottomrule
\caption*{\scriptsize {\bf Fuente:} Servicio Nacional de Medicina Legal y Ciencias Forenses. \\
{\bf Elaborado:} DAIE}
\endlastfoot
\input{tablas/iess_snmlcf_edad_sexo.tex}
\end{longtable}
}

La figura \ref{fig:iess_bar_snmlcf} detalla la distribución por cargo de las y los servidores públicos del SNMLCF, donde se exhibe que el cargo que ocupa el mayor porcentaje de su población es el de \textit{Administrativo} con 87 servidores, seguido por \textit{Analista 2} con 52. Los cargos con menor porcentaje de empleados son \textit{Especialista} y \textit{Directivo} con 10 y 2 servidores respectivamente. Además, la tabla \ref{tab:iess_snmlcf_cargo_sexo} muestra su distribución por cargo y sexo. Se visualiza que, a excepción del cargo \textit{Administrativo}, el porcentaje de mujeres y hombres en cada puesto se encuentra nivelado.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del SNMLCF}
\label{fig:iess_bar_snmlcf}
\includegraphics[scale=1]{graficos/iess_bar_snmlcf.png}
\caption*{\scriptsize {\bf Fuente:} Servicio Nacional de Medicina Legal y Ciencias Forenses \\
{\bf Elaborado:} DAIE}
\end{figure}

La tabla \ref{tab:iess_snmlcf_cargo_salario} detalla la media del salario para cada cargo del SNMLCF, en ella se visualiza que el salario promedio se encuentra en concordancia con la jerarquía de puestos definida en el COESCOP para esta entidad, obviando el cargo \textit{Administrativo} que no se contempla en el mencionado código. Además, los valores son similares a los definidos en la resolución MDT-2019-190.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del SNMLCF}
\label{tab:iess_snmlcf_cargo_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_snmlcf_cargo_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Servicio Nacional de Medicina Legal y Ciencias Forenses \\
{\bf Elaborado:} DAIE}
\end{table}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del SNMLCF}
\label{tab:iess_snmlcf_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_snmlcf_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Servicio Nacional de Medicina Legal y Ciencias Forenses \\
{\bf Elaborado:} DAIE}
\end{table}

% %---------------------------------------------------------------------------------------------------
\subsection{Cuerpo de Vigilancia Aduanera}
\label{chp_demog:aduaneros}

%---------------------------------------------------------------------------------------------------
Para el presente estudio se considera el número total de servidores públicos del Cuerpo de Vigilancia Aduanera a marzo del 2022, que es de 1.625 servidores. En la figura \ref{fig:iess_pir_aduaneros} y tabla \ref{tab:iess_aduaneros_edad_sexo} se muestra la distribución por edad y sexo de los mismos, éstas reflejan que el 31,02\% del personal son mujeres y el 68,98\% son hombres. Adicionalmente, el 31,88\% del total de empleados de esta entidad se encuentra entre los 30 y 40 años.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Vigilancia Aduanera}
\label{tab:iess_aduaneros_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_aduaneros_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Cuerpo de Vigilancia Aduanera \\
{\bf Elaborado:} DAIE}
\end{table}

En la figura \ref{fig:iess_bar_aduaneros} se detalla la distribución por cargo de las y los servidores públicos del Cuerpo de Vigilancia Aduanera, misma que refleja que el puesto que contempla la mayor cantidad de servidores públicos de la presente entidad es \textit{Administrativo} con 859 servidores, seguido de \textit{Vigilante Aduanero 1} con 399 servidores. Por otro lado, los cargos que representan una minoría en la población de trabajadores son \textit{Inspector de Vigilancia 3} e \textit{Inspector de Vigilancia 1}, con 32 y 23 servidores respectivamente. 

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Vigilancia Aduanera}
\label{fig:iess_pir_aduaneros}
\includegraphics[scale=1]{graficos/iess_pir_aduaneros.png}
\caption*{\scriptsize {\bf Fuente:} Cuerpo de Vigilancia Aduanera \\
{\bf Elaborado:} DAIE}
\end{figure}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Vigilancia Aduanera}
\label{fig:iess_bar_aduaneros}
\includegraphics[scale=1]{graficos/iess_bar_aduaneros.png}
\caption*{\scriptsize {\bf Fuente:} Cuerpo de Vigilancia Aduanera \\
{\bf Elaborado:} DAIE}
\end{figure}


La tabla \ref{tab:iess_aduaneros_cargo_sexo} muestra la distribución por cargo y sexo del personal total del Cuerpo de Vigilancia Aduanera, donde se constata que en los cargos \textit{Inspector de Vigilancia} 2 y 3 no existe población femenina, mientras que en los cargos \textit{Vigilante Aduanero} 1 y 2 existe una clara mayoría de población masculina sobre la femenina.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del Cuerpo de Vigilancia Aduanera}
\label{tab:iess_aduaneros_cargo_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_aduaneros_cargo_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Cuerpo de Vigilancia Aduanera \\
{\bf Elaborado:} DAIE}
\end{table}

La tabla \ref{tab:iess_aduaneros_cargo_salario} contiene el salario promedio por cada cargo del Cuerpo de Vigilancia Aduanera, en la misma queda en evidencia que se respeta el orden jerárquico establecido en el COESCOP. Adicionalmente, de acuerdo con el Oficio Nro. SENAE-DNH-2020-0478-OF, se observa que el salario promedio de \textit{Vigilante Aduanero 1} corresponde al salario de \textit{Vigilante de aduana 4°} del COESCOP, el de \textit{Vigilante Aduanero 2} corresponde al de \textit{Vigilante de aduana 2°} y los de \textit{Inspector de Vigilancia 1, 2, 3} a los salarios de \textit{Vigilante de aduana 1°, Supervisor de aduana 1°} e \textit{Inspector}, respectivamente.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Vigilancia Aduanera}
\label{tab:iess_aduaneros_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_aduaneros_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Cuerpo de Vigilancia Aduanera \\
{\bf Elaborado:} DAIE}
\end{table}

% %---------------------------------------------------------------------------------------------------
\subsection{Cuerpo de Vigilancia de la Comisión de Tránsito del Ecuador}
\label{chp_demog:cte}

%---------------------------------------------------------------------------------------------------
Para el presente estudio se considera el número de servidores públicos de la Comisión de Tránsito del Ecuador (CTE) a marzo del 2022, que es de 5.107 servidores. En la figura \ref{fig:iess_pir_cte} y tabla \ref{tab:iess_cte_edad_sexo} se muestra la distribución por edad y sexo de las y los servidores públicos de la mencionada entidad. En ellas se visualiza que el 10,41\% del personal son mujeres y el 89,59\% son hombres. Además, el 47,09\% de la población total de empleados de esta entidad tiene entre 30 y 40 años.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal de la CTE}
\label{fig:iess_pir_cte}
\includegraphics[scale=1]{graficos/iess_pir_cte.png}
\caption*{\scriptsize {\bf Fuente:} Comisión de Tránsito del Ecuador \\
{\bf Elaborado:} DAIE}
\end{figure}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal de la CTE}
\label{fig:iess_bar_cte}
\includegraphics[scale=1]{graficos/iess_bar_cte.png}
\caption*{\scriptsize {\bf Fuente:} Comisión de Tránsito del Ecuador \\
{\bf Elaborado:} DAIE}
\end{figure}

La figura \ref{fig:iess_bar_cte} detalla la distribución por cargo de las y los servidores públicos de la Comisión de Tránsito del Ecuador e indica que el cargo que concentra la mayor cantidad de trabajadores es \textit{Agente de Tránsito 3} con un total de 668; seguidamente se encuentra el cargo \textit{Administrativo} con 220 servidores. En cambio, los cargos con menor cantidad de servidores son \textit{Prefecto} y \textit{Prefecto Jefe}, con 13 y 27 servidores respectivamente.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo de la CTE}
\label{tab:iess_cte_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_cte_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Comisión de Tránsito del Ecuador \\
{\bf Elaborado:} DAIE}
\end{table}

En la tabla \ref{tab:iess_cte_cargo_sexo} se muestra la distribución por cargo y sexo de los trabajadores de esta institución. En ella se observa que en los cargos \textit{Agente de Tránsito 1, Agente de Tránsito 4, Prefecto, Prefecto Jefe, Subinspector de Tránsito 1} y \textit{Subinspector de Tránsito 2} no existe población femenina. También, en el cargo \textit{Agente de Tránsito 3} se visualiza una mayoría poblacional masculina.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal de la CTE}
\label{tab:iess_cte_cargo_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_cte_cargo_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Comisión de Tránsito del Ecuador \\
{\bf Elaborado:} DAIE}
\end{table}

La tabla \ref{tab:iess_cte_cargo_salario} muestra los salarios promedio de cada cargo de la Comisión de Tránsito del Ecuador ordenados de menor a mayor, se visibiliza que, a excepción de \textit{Inspector}, los salarios promedio respetan la jerarquía propuesta en el COESCOP.


{\fontsize{11}{13}\selectfont
\begin{longtable}[H]{lr}
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal de la CTE}
\label{tab:iess_cte_cargo_salario} \\
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\endfirsthead
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\endhead
\hline
\multicolumn{2}{r}{continúa...} \\
\endfoot
%\bottomrule
\caption*{\scriptsize {\bf Fuente:} Comisión de Tránsito del Ecuador \\
{\bf Elaborado:} DAIE}
\endlastfoot
\input{tablas/iess_cte_cargo_salario.tex}
\end{longtable}
}

% %---------------------------------------------------------------------------------------------------
\subsection{Cuerpo de Seguridad y Vigilancia Penitenciaria}
\label{chp_demog:snai}

%---------------------------------------------------------------------------------------------------
Para el presente estudio se considera el número de servidores públicos del Servicio Nacional de Atención Integral a Personas Adultas Privadas de la Libertad y a Adolescentes Infractores (SNAI) a marzo del 2022, que es de 2.945 servidores. La figura \ref{fig:iess_pir_snai} y tabla \ref{tab:iess_snai_edad_sexo} muestran la distribución por edad y sexo de las y los servidores públicos de la mencionada entidad. En ellas se puede evidenciar que, del total de empleados de esta institución, el 37,22\% son mujeres y el 62,78\% son hombres. Más aún, el 41,90\% de los mismos tiene entre 30 y 40 años.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del SNAI}
\label{fig:iess_pir_snai}
\includegraphics[scale=1]{graficos/iess_pir_snai.png}
\caption*{\scriptsize {\bf Fuente:} Servicio Nacional de Atención Integral a Personas Adultas Privadas de la Libertad y a Adolescentes Infractores \\
{\bf Elaborado:} DAIE}
\end{figure}


La figura \ref{fig:iess_bar_snai} detalla la distribución por cargo de las y los servidores públicos del SNAI, donde se observa que el puesto que contiene a la mayoría de los servidores públicos de esta institución es \textit{Administrativo} con 1.232 servidores, seguido por \textit{Agente de Seguridad Penitenciaria 3}, con 768 de ellos. Después, los cargos que concentran una minoría de servidores del SNAI son \textit{Subjefe de Seguridad Penitenciaria} e \textit{Inspector de Seguridad Penitenciaria}, con 2 y 46 servidores respectivamente.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del SNAI}
\label{tab:iess_snai_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_snai_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Servicio Nacional de Atención Integral a Personas Adultas Privadas de la Libertad y a Adolescentes Infractores \\
{\bf Elaborado:} DAIE}
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del SNAI}
\label{fig:iess_bar_snai}
\includegraphics[scale=1]{graficos/iess_bar_snai.png}
\caption*{\scriptsize {\bf Fuente:} Servicio Nacional de Atención Integral a Personas Adultas Privadas de la Libertad y a Adolescentes Infractores.\\
{\bf Elaborado:} DAIE}
\end{figure}

En la tabla \ref{tab:iess_snai_cargo_sexo} se muestra la distribución por cargo y sexo de los empleados de este ente. En ella se pone en manifiesto que en todos los cargos existe una mayoría de población masculina, siendo \textit{Agente de Seguridad Penitenciaria} 1 y 3 los cargos donde esta diferencia de población masculina y femenina es mayor.

La tabla \ref{tab:iess_snai_cargo_salario} contiene los salarios promedio del Cuerpo de Vigilancia y Seguridad Penitenciaria, donde se observa que se respeta el grado reflejado en el COESCOP para esta entidad. Más aún, los salarios promedio son similares a los dispuestos en la resolución MDT-2019-185.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del SNAI}
\label{tab:iess_snai_cargo_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_snai_cargo_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Servicio Nacional de Atención Integral a Personas Adultas Privadas de la Libertad y a Adolescentes Infractores \\
{\bf Elaborado:} DAIE}
\end{table}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del SNAI}
\label{tab:iess_snai_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_snai_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Servicio Nacional de Atención Integral a Personas Adultas Privadas de la Libertad y a Adolescentes Infractores \\
{\bf Elaborado:} DAIE}
\end{table} 

\newpage

%%-------------------------------------------------------------------------------------------------
\subsection{Cuerpos de Agentes de Control Municipal o Metropolitano}
\label{chp_demog:control}
Para el presente estudio se considera el número de servidores públicos del Cuerpo de Agentes de Control Municipal o Metropolitano. Para la realización de este análisis se tomaron en cuenta las ciudades: Ambato, Durán, Esmeraldas, Guayaquil, Machala, Portoviejo, Quito y Santo Domingo, debido que el resto de los Gobiernos Autónomos Descentralizados Municipales y Metropolitano no han publicado el listado de servidores y remuneraciones, de acuerdo con el artículo 7 de la Ley Orgánica de Transparencia y Acceso a la Información Pública - LOTAIP, que establece: "\textit{c) La remuneración mensual por puesto y todo ingreso adicional, incluso el sistema de compensación, según lo establezcan las disposiciones correspondientes}".

Por otra parte, no es competencia del IESS elaborar planes de carrera o homologar roles o grados de los agentes que se encuentren bajo el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público (COESCOP).

%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de control de Ambato}
\label{chp_demog:control_ambato}

El Cuerpo de Agentes de Control de Ambato consiste en \Sexpr{REP$c_ambato_dem_1} agentes, de los cuales \Sexpr{REP$c_ambato_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$c_ambato_dem_2_m} años; y \Sexpr{REP$c_ambato_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$c_ambato_dem_2_f} años. El \Sexpr{REP$c_ambato_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_control_ambato_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_control_ambato} se representa la pirámide poblacional de los agentes de control de Ambato.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Control Municipal de Ambato}
\label{fig:iess_pir_control_ambato}
\includegraphics[scale=1]{graficos/iess_pir_control_ambato.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato \\
{\bf Elaborado:} DAIE}
\end{figure}


{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Control Municipal de Ambato}
\label{tab:iess_control_ambato_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_ambato_sexo.tex}
\end{longtable}
}
}

El Cuerpo de Agentes de Control de Ambato se compone de \Sexpr{REP$c_ambato_dem_4_1} agentes de control 1, \Sexpr{REP$c_ambato_dem_4_2} inspectores de control y \Sexpr{REP$c_ambato_dem_4_3} jefe de control. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_control_ambato_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Control Municipal de Ambato}
\label{tab:iess_control_ambato_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_ambato_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Control Municipal de Ambato}
\label{fig:iess_bar_control_ambato}
\includegraphics[scale=0.8]{graficos/iess_bar_control_ambato.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio de un Agente de Control 1 es USD \Sexpr{REP$c_ambato_dem_5_1}; el Inspector de Control es USD \Sexpr{REP$c_ambato_dem_5_2} y del Jefe de Control es USD \Sexpr{REP$c_ambato_dem_5_3} (ver la tabla \ref{tab:iess_metropolitanos_ambato_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Control Municipal de Ambato}
\label{tab:iess_metropolitanos_ambato_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_control_ambato_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato  \\
{\bf Elaborado:} DAIE }
\end{table}

%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de control de Durán}
\label{chp_demog:control_duran}

El Cuerpo de Agentes de Control de Durán consiste en \Sexpr{REP$c_duran_dem_1} agentes, de los cuales \Sexpr{REP$c_duran_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$c_duran_dem_2_m} años; y \Sexpr{REP$c_duran_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$c_duran_dem_2_f} años. El \Sexpr{REP$c_duran_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_control_duran_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_control_duran} se representa la pirámide poblacional de los agentes de control de Durán.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Control Municipal de Durán}
\label{fig:iess_pir_control_duran}
\includegraphics[scale=1]{graficos/iess_pir_control_duran.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Durán \\
{\bf Elaborado:} DAIE}
\end{figure}

El Cuerpo de Agentes de Control de Durán se compone de \Sexpr{REP$c_duran_dem_4_1} agentes de control 1 y \Sexpr{REP$c_duran_dem_4_2} jefes de control. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_control_duran_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Control Municipal de Durán}
\label{tab:iess_control_duran_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Durán \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_duran_sexo.tex}
\end{longtable}
}
}

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Control Municipal de Durán}
\label{tab:iess_control_duran_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Durán \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_duran_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Control Municipal de Durán}
\label{fig:iess_bar_control_duran}
\includegraphics[scale=0.8]{graficos/iess_bar_control_duran.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Durán \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio de un Agente de Control 1 es USD \Sexpr{REP$c_duran_dem_5_1} y del jefe de Control es USD \Sexpr{REP$c_duran_dem_5_2} (ver la tabla \ref{tab:iess_metropolitanos_duran_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Control Municipal de Durán}
\label{tab:iess_metropolitanos_duran_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_control_duran_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Durán \\
{\bf Elaborado:} DAIE }
\end{table}

%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de control de Esmeraldas}
\label{chp_demog:control_esmeraldas}

El Cuerpo de Agentes de Control de Esmeraldas se compone de \Sexpr{REP$c_esmeraldas_dem_1} agentes, de los cuales \Sexpr{REP$c_esmeraldas_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$c_esmeraldas_dem_2_m} años; y \Sexpr{REP$c_esmeraldas_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$c_esmeraldas_dem_2_f} años. El \Sexpr{REP$c_esmeraldas_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_control_esmeraldas_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_control_esmeraldas} se representa la pirámide poblacional de los agentes de control de Esmeraldas.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Control Municipal de Esmeraldas}
\label{fig:iess_pir_control_esmeraldas}
\includegraphics[scale=1]{graficos/iess_pir_control_esmeraldas.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Esmeraldas \\
{\bf Elaborado:} DAIE}
\end{figure}

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Control Municipal de Esmeraldas}
\label{tab:iess_control_esmeraldas_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Esmeraldas \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_esmeraldas_sexo.tex}
\end{longtable}
}
}


El Cuerpo de Agentes de Control de Esmeraldas se compone de \Sexpr{REP$c_esmeraldas_dem_4_1} agentes de control 1,  \Sexpr{REP$c_esmeraldas_dem_4_2} subinspectores de control y \Sexpr{REP$c_esmeraldas_dem_4_3} jefe de control. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_control_esmeraldas_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Control Municipal de Esmeraldas}
\label{tab:iess_control_esmeraldas_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Esmeraldas \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_esmeraldas_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Control Municipal de Esmeraldas}
\label{fig:iess_bar_control_esmeraldas}
\includegraphics[scale=0.8]{graficos/iess_bar_control_esmeraldas.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Esmeraldas \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio de un Agente de Control 1 es USD \Sexpr{REP$c_esmeraldas_dem_5_1}, del subinspector de control es USD \Sexpr{REP$c_esmeraldas_dem_5_2} y del jefe de Control es USD \Sexpr{REP$c_esmeraldas_dem_5_3} (ver la tabla \ref{tab:iess_metropolitanos_esmeraldas_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Control Municipal de Esmeraldas}
\label{tab:iess_metropolitanos_esmeraldas_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_control_esmeraldas_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Esmeraldas \\
{\bf Elaborado:} DAIE }
\end{table}


%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de control de Guayaquil}
\label{chp_demog:control_guayaquil}

El Cuerpo de Agentes de Control de Guayaquil se compone de \Sexpr{REP$c_guayaquil_dem_1} agentes, de los cuales \Sexpr{REP$c_guayaquil_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$c_guayaquil_dem_2_m} años; y \Sexpr{REP$c_guayaquil_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$c_guayaquil_dem_2_f} años. El \Sexpr{REP$c_guayaquil_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_control_guayaquil_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_control_guayaquil} se representa la pirámide poblacional de los agentes de control de Guayaquil.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Control Municipal de Guayaquil}
\label{fig:iess_pir_control_guayaquil}
\includegraphics[scale=1]{graficos/iess_pir_control_guayaquil.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE}
\end{figure}

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Control Municipal de Guayaquil}
\label{tab:iess_control_guayaquil_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_guayaquil_sexo.tex}
\end{longtable}
}
}


El Cuerpo de Agentes de Control de Guayaquil se compone de \Sexpr{REP$c_guayaquil_dem_4_1} agentes de control 1, \Sexpr{REP$c_guayaquil_dem_4_2} agentes de control 3, \Sexpr{REP$c_guayaquil_dem_4_3} agentes de control 2, 23 agentes de control 4 y 6 jefes de control. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_control_guayaquil_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{10}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Control Municipal de Guayaquil}
\label{tab:iess_control_guayaquil_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_guayaquil_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Control Municipal de Guayaquil}
\label{fig:iess_bar_control_guayaquil}
\includegraphics[scale=0.8]{graficos/iess_bar_control_guayaquil.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio de los agentes es USD \Sexpr{REP$c_guayaquil_dem_5_1} para el Agente de Control 1, USD \Sexpr{REP$c_guayaquil_dem_5_2} para el Agente de Control 3, USD \Sexpr{REP$c_guayaquil_dem_5_3} para el Agente de Control 2, USD 985,22 para el Agente de Control 4 y USD 2.675,33 para el Jefe de Control (ver la tabla \ref{tab:iess_metropolitanos_guayaquil_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Control Municipal de Guayaquil}
\label{tab:iess_metropolitanos_guayaquil_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_control_guayaquil_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE }
\end{table}


%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de control de Latacunga}
\label{chp_demog:control_latacunga}

El Cuerpo de Agentes de Control de Latacunga se compone de \Sexpr{REP$c_latacunga_dem_1} agentes, de los cuales \Sexpr{REP$c_latacunga_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$c_latacunga_dem_2_m} años; y \Sexpr{REP$c_latacunga_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$c_latacunga_dem_2_f} años. El \Sexpr{REP$c_latacunga_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_control_latacunga_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_control_latacunga} se representa la pirámide poblacional de los agentes de control de Latacunga.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Control Municipal de Latacunga}
\label{fig:iess_pir_control_latacunga}
\includegraphics[scale=1]{graficos/iess_pir_control_latacunga.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Latacunga \\
{\bf Elaborado:} DAIE}
\end{figure}

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Control Municipal de Latacunga}
\label{tab:iess_control_latacunga_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Latacunga \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_latacunga_sexo.tex}
\end{longtable}
}
}

El Cuerpo de Agentes de Control de Latacunga se compone de \Sexpr{REP$c_latacunga_dem_4_1} agentes de control 1. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_control_latacunga_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Control Municipal de Latacunga}
\label{tab:iess_control_latacunga_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Latacunga \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_latacunga_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Control Municipal de Latacunga}
\label{fig:iess_bar_control_latacunga}
\includegraphics[scale=0.8]{graficos/iess_bar_control_latacunga.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Latacunga \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio de un Agente de Control 1 es USD \Sexpr{REP$c_latacunga_dem_5_1} (ver la tabla \ref{tab:iess_metropolitanos_latacunga_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Control Municipal de Latacunga}
\label{tab:iess_metropolitanos_latacunga_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_control_latacunga_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Latacunga \\
{\bf Elaborado:} DAIE }
\end{table}


%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de control de Machala}
\label{chp_demog:control_machala}

El Cuerpo de Agentes de Control de Machala se compone de \Sexpr{REP$c_machala_dem_1} agentes, de los cuales \Sexpr{REP$c_machala_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$c_machala_dem_2_m} años; y \Sexpr{REP$c_machala_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$c_machala_dem_2_f} años. El \Sexpr{REP$c_machala_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_control_machala_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_control_machala} se representa la pirámide poblacional de los agentes de control de Machala.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Control Municipal de Machala}
\label{fig:iess_pir_control_machala}
\includegraphics[scale=1]{graficos/iess_pir_control_machala.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE}
\end{figure}

El Cuerpo de Agentes de Control de Machala se compone de \Sexpr{REP$c_machala_dem_4_1} agentes de control 1 y \Sexpr{REP$c_machala_dem_4_2} jefe de control. No se consideran puestos administrativos al no ser mencionados en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_control_machala_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Control Municipal de Machala}
\label{tab:iess_control_machala_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_machala_sexo.tex}
\end{longtable}
}
}

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Control Municipal de Machala}
\label{tab:iess_control_machala_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_machala_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Control Municipal de Machala}
\label{fig:iess_bar_control_machala}
\includegraphics[scale=0.8]{graficos/iess_bar_control_machala.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio de un Agente de Control 1 es USD \Sexpr{REP$c_machala_dem_5_1} y del Jefe de Control es USD \Sexpr{REP$c_machala_dem_5_2} (ver la tabla \ref{tab:iess_metropolitanos_machala_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Control Municipal de Machala}
\label{tab:iess_metropolitanos_machala_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_control_machala_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE }
\end{table}

%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de control de Portoviejo}
\label{chp_demog:control_p_viejo}

El Cuerpo de Agentes de Control de Portoviejo se compone de \Sexpr{REP$c_p_viejo_dem_1} agentes, de los cuales \Sexpr{REP$c_p_viejo_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$c_p_viejo_dem_2_m} años; y \Sexpr{REP$c_p_viejo_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$c_p_viejo_dem_2_f} años. El \Sexpr{REP$c_p_viejo_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_control_p_viejo_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_control_p_viejo} se representa la pirámide poblacional de los agentes de control de Portoviejo

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Control Municipal de Portoviejo}
\label{fig:iess_pir_control_p_viejo}
\includegraphics[scale=1]{graficos/iess_pir_control_p_viejo.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Portoviejo \\
{\bf Elaborado:} DAIE}
\end{figure}

El Cuerpo de Agentes de Control de Portoviejo se compone de \Sexpr{REP$c_p_viejo_dem_4_1} agentes de control 1 y \Sexpr{REP$c_p_viejo_dem_4_2} jefe de control. No se consideran puestos administrativos al no ser mencionados en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_control_p_viejo_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Control Municipal de Portoviejo}
\label{tab:iess_control_p_viejo_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Portoviejo \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_p_viejo_sexo.tex}
\end{longtable}
}
}

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Control Municipal de Portoviejo}
\label{tab:iess_control_p_viejo_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Portoviejo \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_p_viejo_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Control Municipal de Portoviejo}
\label{fig:iess_bar_control_p_viejo}
\includegraphics[scale=0.8]{graficos/iess_bar_control_p_viejo.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Portoviejo \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio de un Agente de Control 1 es USD \Sexpr{REP$c_p_viejo_dem_5_1} y del Jefe de Control es USD \Sexpr{REP$c_p_viejo_dem_5_2} (ver la tabla \ref{tab:iess_metropolitanos_p_viejo_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Control Municipal de Portoviejo}
\label{tab:iess_metropolitanos_p_viejo_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_control_p_viejo_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Portoviejo \\
{\bf Elaborado:} DAIE }
\end{table}

%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de control de Santo Domingo}
\label{chp_demog:control_s_domingo}

El Cuerpo de Agentes de Control de Santo Domingo se compone de \Sexpr{REP$c_s_domingo_dem_1} agentes, de los cuales \Sexpr{REP$c_s_domingo_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$c_s_domingo_dem_2_m} años; y \Sexpr{REP$c_s_domingo_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$c_s_domingo_dem_2_f} años. El \Sexpr{REP$c_s_domingo_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_control_s_domingo_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_control_s_domingo} se representa la pirámide poblacional de los agentes de control de Santo Domingo.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Control Municipal de Santo Domingo}
\label{fig:iess_pir_control_s_domingo}
\includegraphics[scale=1]{graficos/iess_pir_control_s_domingo.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE}
\end{figure}

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Control Municipal de Santo Domingo}
\label{tab:iess_control_s_domingo_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_s_domingo_sexo.tex}
\end{longtable}
}
}


El Cuerpo de Agentes de Control de Santo Domingo se compone de \Sexpr{REP$c_s_domingo_dem_4_1} agentes de control 1 y \Sexpr{REP$c_s_domingo_dem_4_2} jefe de control. No se consideran puestos administrativos al no ser mencionados en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_control_s_domingo_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Control Municipal de Santo Domingo}
\label{tab:iess_control_s_domingo_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_s_domingo_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Control Municipal de Santo Domingo}
\label{fig:iess_bar_control_s_domingo}
\includegraphics[scale=0.8]{graficos/iess_bar_control_s_domingo.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio de un Agente de Control 1 es USD \Sexpr{REP$c_s_domingo_dem_5_1} y del Jefe de Control es USD \Sexpr{REP$c_s_domingo_dem_5_2} (ver la tabla \ref{tab:iess_metropolitanos_s_domingo_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Control Municipal de Santo Domingo}
\label{tab:iess_metropolitanos_s_domingo_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_control_s_domingo_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE }
\end{table}


%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de control de Quito}
\label{chp_demog:control_quito}

El Cuerpo de Agentes de Control de Quito se compone de \Sexpr{REP$c_quito_dem_1} agentes, de los cuales \Sexpr{REP$c_quito_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$c_quito_dem_2_m} años; y \Sexpr{REP$c_quito_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$c_quito_dem_2_f} años. El \Sexpr{REP$c_quito_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_control_quito_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_control_quito} se representa la pirámide poblacional de los agentes de control de Quito.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Control Municipal de Quito}
\label{fig:iess_pir_control_quito}
\includegraphics[scale=1]{graficos/iess_pir_control_quito.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
{\bf Elaborado:} DAIE}
\end{figure}

El Cuerpo de Agentes de Control de Quito se compone de \Sexpr{REP$c_quito_dem_4_1} agentes de control 1 y \Sexpr{REP$c_quito_dem_4_2} jefes de control. No se consideran puestos administrativos al no ser mencionados en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_control_quito_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Control Municipal de Quito}
\label{tab:iess_control_quito_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_quito_sexo.tex}
\end{longtable}
}
}


{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Control Municipal de Quito}
\label{tab:iess_control_quito_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_control_quito_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Control Municipal de Quito}
\label{fig:iess_bar_control_quito}
\includegraphics[scale=0.8]{graficos/iess_bar_control_quito.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio de un Agente de Control 1 es USD \Sexpr{REP$c_quito_dem_5_1} y del jefe de Control es USD \Sexpr{REP$c_quito_dem_5_2} (ver la tabla \ref{tab:iess_metropolitanos_quito_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Control Municipal de Quito}
\label{tab:iess_metropolitanos_quito_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_control_quito_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
{\bf Elaborado:} DAIE }
\end{table}

%%--------------------------------------------------------------------------------------------------
\subsubsection{Policías Municipales de La Concordia}
\label{chp_demog:metropolitanos_concordia}

En la tabla \ref{tab:iess_metropolitanos_concordia_edad_sexo} y la figura \ref{fig:iess_pir_metropolitanos_concordia} se muestran la distribución por edad y sexo de las y los trabajadores de la presente entidad. A junio del 2022, el total de policías municipales de La Concordia es de 23, de los cuales el 21,74\% son mujeres y el 78,26\% son hombres. Además, del total del personal de esta entidad, el 60,87\% no sobrepasa los 40 años. La edad promedio en los hombres es 39,10 años y 42,2 años en las mujeres.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo de los policías municipales de La Concordia}
\label{fig:iess_pir_metropolitanos_concordia}
\includegraphics[scale=1]{graficos/iess_pir_concordia.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de La Concordia \\
{\bf Elaborado:} DAIE}
\end{figure}

Como se observa en la figura \ref{fig:iess_bar_metropolitanos_concordia} y en la tabla \ref{tab:iess_metropolitanos_concordia_cargo} todos los policías de La Concordia tienen el mismo cargo institucional "Policía Municipal". La tabla \ref{tab:iess_metropolitanos_concordia_cargo_salario} corresponde a los salarios promedio los policías municipales de La Concordia por sexo. El salario promedio en los hombres es USD 584,39 y USD 581 en las mujeres, en total el salario promedio de un policía municipal de La Concordia es USD 583,65.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo policías municipales de La Concordia}
\label{tab:iess_metropolitanos_concordia_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_concordia_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de La Concordia \\
{\bf Elaborado:} DAIE}
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo policías municipales de La Concordia}
\label{fig:iess_bar_metropolitanos_concordia}
\includegraphics[scale=0.8]{graficos/iess_bar_concordia.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de La Concordia \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo de los policías municipales de La Concordia}
\label{tab:iess_metropolitanos_concordia_cargo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo institucional & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
%\midrule
\input{tablas/iess_concordia_cargo_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de La Concordia \\
{\bf Elaborado:} DAIE}
\end{table}


\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Control Municipal de La Concordia}
\label{tab:iess_metropolitanos_concordia_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_concordia_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de La Concordia  \\
{\bf Elaborado:} DAIE}
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Salarios promedios por edad y sexo de los policías municiapales de La Concordia}
\label{fig:iess_pir_salarios_concordia}
\includegraphics[scale=0.9]{graficos/iess_pir_salarios_concordia.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de La Concordia \\
{\bf Elaborado:} DAIE}
\end{figure}


% %---------------------------------------------------------------------------------------------------
\subsection{Cuerpos de Agentes Civiles de Tránsito}
\label{chp_demog:transito}
Para el presente estudio se considera el número de servidores públicos del Cuerpo de Agentes de Tránsito Municipal o Metropolitano. Para la realización de este análisis se tomaron en cuenta las ciudades: Cuenca, Durán, Esmeraldas, Guayaquil, Ibarra, Latacunga, Machala, Quito, Santo Domingo,  Ambato,Riobamba y Loja, debido que el resto de los Gobiernos Autónomos Descentralizados Municipales y Metropolitano no han publicado el listado de servidores y remuneraciones, de acuerdo con el artículo 7 de la Ley Orgánica de Transparencia y Acceso a la Información Pública - LOTAIP, que establece: "\textit{c) La remuneración mensual por puesto y todo ingreso adicional, incluso el sistema de compensación, según lo establezcan las disposiciones correspondientes}".

Por otra parte, no es competencia del IESS elaborar planes de carrera o homologar roles o grados de los agentes que se encuentren bajo el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público (COESCOP).

%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de Tránsito de Cuenca}
\label{chp_demog:transito_cuenca}

El Cuerpo de Agentes de Tránsito de Cuenca consiste en \Sexpr{REP$t_cuenca_dem_1} agentes, de los cuales \Sexpr{REP$t_cuenca_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$t_cuenca_dem_2_m} años; y \Sexpr{REP$t_cuenca_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$t_cuenca_dem_2_f} años. El \Sexpr{REP$t_cuenca_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_transito_cuenca_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_transito_cuenca} se representa la pirámide poblacional de los Agentes de Tránsito de Cuenca.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Tránsito de Cuenca}
\label{fig:iess_pir_transito_cuenca}
\includegraphics[scale=0.9]{graficos/iess_pir_transito_cuenca.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Cuenca \\
{\bf Elaborado:} DAIE}
\end{figure}


{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Tránsito de Cuenca}
\label{tab:iess_transito_cuenca_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Cuenca \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_cuenca_sexo.tex}
\end{longtable}
}
}

El Cuerpo de Agentes de Tránsito de Cuenca se compone de \Sexpr{REP$t_cuenca_dem_4_1} agentes de Tránsito 1 y un (\Sexpr{REP$t_cuenca_dem_4_2}) Gerente de Tránsito. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_transito_cuenca_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Tránsito de Cuenca}
\label{tab:iess_transito_cuenca_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Cuenca \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_cuenca_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Tránsito de Cuenca}
\label{fig:iess_bar_transito_cuenca}
\includegraphics[scale=0.8]{graficos/iess_bar_transito_cuenca.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Cuenca \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio es USD \Sexpr{REP$t_cuenca_dem_5_1} para el Agente de Tránsito y USD \Sexpr{REP$t_cuenca_dem_5_2} para el Gerente de Tránsito (ver la tabla \ref{tab:iess_metropolitanos_cuenca_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Tránsito de Cuenca}
\label{tab:iess_metropolitanos_cuenca_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_transito_cuenca_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Cuenca  \\
{\bf Elaborado:} DAIE }
\end{table}

%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de Tránsito de Durán}
\label{chp_demog:transito_duran}

El Cuerpo de Agentes de Tránsito de Durán consiste en \Sexpr{REP$t_duran_dem_1} agentes, de los cuales \Sexpr{REP$t_duran_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$t_duran_dem_2_m} años; y \Sexpr{REP$t_duran_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$t_duran_dem_2_f} años. El \Sexpr{REP$t_duran_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_transito_duran_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_transito_duran} se representa la pirámide poblacional de los Agentes de Tránsito de Durán.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Tránsito de Durán}
\label{tab:iess_transito_duran_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Durán \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_duran_sexo.tex}
\end{longtable}
}
}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Tránsito de Durán}
\label{fig:iess_pir_transito_duran}
\includegraphics[scale=1]{graficos/iess_pir_transito_duran.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Durán \\
{\bf Elaborado:} DAIE}
\end{figure}

El Cuerpo de Agentes de Tránsito de Durán se compone de \Sexpr{REP$t_duran_dem_4_1} agentes de Tránsito 1 y \Sexpr{REP$t_duran_dem_4_2} Subinspectores de Tránsito. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_transito_duran_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{10}{11}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Tránsito de Durán}
\label{tab:iess_transito_duran_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Durán \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_duran_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Tránsito de Durán}
\label{fig:iess_bar_transito_duran}
\includegraphics[scale=0.8]{graficos/iess_bar_transito_duran.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Durán \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio es USD \Sexpr{REP$t_duran_dem_5_1} para el Agente de Tránsito y USD \Sexpr{REP$t_duran_dem_5_2} para el Subinspector de Tránsito (ver la tabla \ref{tab:iess_metropolitanos_duran_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Tránsito de Durán}
\label{tab:iess_metropolitanos_duran_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_transito_duran_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Durán  \\
{\bf Elaborado:} DAIE }
\end{table}

%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de Tránsito de Esmeraldas}
\label{chp_demog:transito_esmeraldas}

El Cuerpo de Agentes de Tránsito de Esmeraldas consiste en \Sexpr{REP$t_esmeraldas_dem_1} agentes, de los cuales \Sexpr{REP$t_esmeraldas_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$t_esmeraldas_dem_2_m} años; y \Sexpr{REP$t_esmeraldas_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$t_esmeraldas_dem_2_f} años. El \Sexpr{REP$t_esmeraldas_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_transito_esmeraldas_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_transito_esmeraldas} se representa la pirámide poblacional de los Agentes de Tránsito de Esmeraldas.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Tránsito de Esmeraldas}
\label{tab:iess_transito_esmeraldas_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Esmeraldas \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_esmeraldas_sexo.tex}
\end{longtable}
}
}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Tránsito de Esmeraldas}
\label{fig:iess_pir_transito_esmeraldas}
\includegraphics[scale=1]{graficos/iess_pir_transito_esmeraldas.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Esmeraldas \\
{\bf Elaborado:} DAIE}
\end{figure}

El Cuerpo de Agentes de Tránsito de Esmeraldas se compone de \Sexpr{REP$t_esmeraldas_dem_4_1} agentes de Tránsito 1, \Sexpr{REP$t_esmeraldas_dem_4_2} Inspectores de Tránsito y un (1) Director de Tránsito. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_transito_esmeraldas_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Tránsito de Esmeraldas}
\label{tab:iess_transito_esmeraldas_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Esmeraldas \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_esmeraldas_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Tránsito de Esmeraldas}
\label{fig:iess_bar_transito_esmeraldas}
\includegraphics[scale=0.8]{graficos/iess_bar_transito_esmeraldas.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Esmeraldas \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio es USD \Sexpr{REP$t_esmeraldas_dem_5_1} para el Agente de Tránsito, USD \Sexpr{REP$t_esmeraldas_dem_5_2} para el Inspector de Tránsito y  USD \Sexpr{REP$t_esmeraldas_dem_5_3} para el Director de tránsito (ver la tabla \ref{tab:iess_metropolitanos_esmeraldas_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Tránsito de Esmeraldas}
\label{tab:iess_metropolitanos_esmeraldas_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_transito_esmeraldas_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Esmeraldas  \\
{\bf Elaborado:} DAIE }
\end{table}

%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de Tránsito de Guayaquil}
\label{chp_demog:transito_guayaquil}

El Cuerpo de Agentes de Tránsito de Guayaquil consiste en \Sexpr{REP$t_guayaquil_dem_1} agentes, de los cuales \Sexpr{REP$t_guayaquil_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$t_guayaquil_dem_2_m} años; y \Sexpr{REP$t_guayaquil_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$t_guayaquil_dem_2_f} años. El \Sexpr{REP$t_guayaquil_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_transito_guayaquil_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_transito_guayaquil} se representa la pirámide poblacional de los Agentes de Tránsito de Guayaquil.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Tránsito de Guayaquil}
\label{tab:iess_transito_guayaquil_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_guayaquil_sexo.tex}
\end{longtable}
}
}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Tránsito de Guayaquil}
\label{fig:iess_pir_transito_guayaquil}
\includegraphics[scale=1]{graficos/iess_pir_transito_guayaquil.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE}
\end{figure}


El Cuerpo de Agentes de Tránsito de Guayaquil se compone de \Sexpr{REP$t_guayaquil_dem_4_1} agentes de Tránsito 1, \Sexpr{REP$t_guayaquil_dem_4_2} Inspectores de Tránsito y un (\Sexpr{REP$t_guayaquil_dem_4_3}) Director de Control de Tránsito. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_transito_guayaquil_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{10}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Tránsito de Guayaquil}
\label{tab:iess_transito_guayaquil_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_guayaquil_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Tránsito de Guayaquil}
\label{fig:iess_bar_transito_guayaquil}
\includegraphics[scale=0.8]{graficos/iess_bar_transito_guayaquil.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Tránsito de Guayaquil}
\label{tab:iess_metropolitanos_guayaquil_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_transito_guayaquil_sal.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil  \\
{\bf Elaborado:} DAIE }
\end{table}

El salario mensual promedio es USD \Sexpr{REP$t_guayaquil_dem_5_1} para el Agente de Tránsito, USD \Sexpr{REP$t_guayaquil_dem_5_2} para el Inspector de tránsito y USD \Sexpr{REP$t_guayaquil_dem_5_3} para el Director de Control de Tránsito (ver la tabla \ref{tab:iess_metropolitanos_guayaquil_cargo_salario}).
%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de Tránsito de Ibarra}
\label{chp_demog:transito_ibarra}

El Cuerpo de Agentes de Tránsito de Ibarra consiste en \Sexpr{REP$t_ibarra_dem_1} agentes, de los cuales \Sexpr{REP$t_ibarra_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$t_ibarra_dem_2_m} años; y \Sexpr{REP$t_ibarra_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$t_ibarra_dem_2_f} años. 

{\setlength{\tabcolsep}{5pt}
{\fontsize{10}{11}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Tránsito de Ibarra}
\label{tab:iess_transito_ibarra_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Ibarra \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_ibarra_sexo.tex}
\end{longtable}
}
}

El \Sexpr{REP$t_ibarra_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_transito_ibarra_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_transito_ibarra} se representa la pirámide poblacional de los Agentes de Tránsito de Ibarra.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Tránsito de Ibarra}
\label{fig:iess_pir_transito_ibarra}
\includegraphics[scale=1]{graficos/iess_pir_transito_ibarra.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ibarra \\
{\bf Elaborado:} DAIE}
\end{figure}

El Cuerpo de Agentes de Tránsito de Ibarra se compone de \Sexpr{REP$t_ibarra_dem_4_1} agentes de Tránsito 1 y un (\Sexpr{REP$t_ibarra_dem_4_2}) Gerente de Tránsito. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_transito_ibarra_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Tránsito de Ibarra}
\label{tab:iess_transito_ibarra_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Ibarra \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_ibarra_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Tránsito de Ibarra}
\label{fig:iess_bar_transito_ibarra}
\includegraphics[scale=0.8]{graficos/iess_bar_transito_ibarra.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ibarra \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio es USD \Sexpr{REP$t_ibarra_dem_5_1} para el Agente de Tránsito y USD \Sexpr{REP$t_ibarra_dem_5_2} para el Gerente de Tránsito (ver la tabla \ref{tab:iess_metropolitanos_ibarra_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Tránsito de Ibarra}
\label{tab:iess_metropolitanos_ibarra_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_transito_ibarra_sal.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ibarra  \\
{\bf Elaborado:} DAIE }
\end{table}


%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de Tránsito de Latacunga}
\label{chp_demog:transito_latacunga}

El Cuerpo de Agentes de Tránsito de Latacunga consiste en \Sexpr{REP$t_latacunga_dem_1} agentes, de los cuales \Sexpr{REP$t_latacunga_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$t_latacunga_dem_2_m} años; y \Sexpr{REP$t_latacunga_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$t_latacunga_dem_2_f} años. El \Sexpr{REP$t_latacunga_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_transito_latacunga_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_transito_latacunga} se representa la pirámide poblacional de los Agentes de Tránsito de Latacunga.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{13}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Tránsito de Latacunga}
\label{tab:iess_transito_latacunga_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Latacunga \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_latacunga_sexo.tex}
\end{longtable}
}
}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Tránsito de Latacunga}
\label{fig:iess_pir_transito_latacunga}
\includegraphics[scale=1.1]{graficos/iess_pir_transito_latacunga.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Latacunga \\
{\bf Elaborado:} DAIE}
\end{figure}

El Cuerpo de Agentes de Tránsito de Latacunga se compone de \Sexpr{REP$t_latacunga_dem_4_1} agentes de Tránsito 1. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_transito_latacunga_puestos} se presenta más detalle de la distribución de puestos por sexo. El salario mensual promedio es USD \Sexpr{REP$t_latacunga_dem_5_1} para el Agente de Tránsito (ver la tabla \ref{tab:iess_metropolitanos_latacunga_cargo_salario}).


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Tránsito de Latacunga}
\label{fig:iess_bar_transito_latacunga}
\includegraphics[scale=0.8]{graficos/iess_bar_transito_latacunga.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Latacunga \\
{\bf Elaborado:} DAIE}
\end{figure}



{\setlength{\tabcolsep}{5pt}
{\fontsize{10}{11}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Tránsito de Latacunga}
\label{tab:iess_transito_latacunga_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Latacunga \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_latacunga_puestos.tex}
\end{longtable}
}
}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Tránsito de Latacunga}
\label{tab:iess_metropolitanos_latacunga_cargo_salario}
\scalebox{0.85}{
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_transito_latacunga_sal.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Latacunga  \\
{\bf Elaborado:} DAIE }
\end{table}

%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de Tránsito de Machala}
\label{chp_demog:transito_machala}

El Cuerpo de Agentes de Tránsito de Machala consiste en \Sexpr{REP$t_machala_dem_1} agentes, de los cuales \Sexpr{REP$t_machala_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$t_machala_dem_2_m} años; y \Sexpr{REP$t_machala_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$t_machala_dem_2_f} años. El \Sexpr{REP$t_machala_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_transito_machala_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_transito_machala} se representa la pirámide poblacional de los Agentes de Tránsito de Machala.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Tránsito de Machala}
\label{fig:iess_pir_transito_machala}
\includegraphics[scale=0.92]{graficos/iess_pir_transito_machala.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE}
\end{figure}


{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Tránsito de Machala}
\label{tab:iess_transito_machala_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_machala_sexo.tex}
\end{longtable}
}
}

El Cuerpo de Agentes de Tránsito de Machala se compone de \Sexpr{REP$t_machala_dem_4_1} agentes de Tránsito 1. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_transito_machala_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Tránsito de Machala}
\label{tab:iess_transito_machala_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_machala_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Tránsito de Machala}
\label{fig:iess_bar_transito_machala}
\includegraphics[scale=0.8]{graficos/iess_bar_transito_machala.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio es USD \Sexpr{REP$t_machala_dem_5_1} para el Agente de Tránsito (ver la tabla \ref{tab:iess_metropolitanos_machala_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Tránsito de Machala}
\label{tab:iess_metropolitanos_machala_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_transito_machala_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala  \\
{\bf Elaborado:} DAIE }
\end{table}


%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de Tránsito de Quito}
\label{chp_demog:transito_quito}

El Cuerpo de Agentes de Tránsito de Quito consiste en \Sexpr{REP$t_quito_dem_1} agentes, de los cuales \Sexpr{REP$t_quito_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$t_quito_dem_2_m} años; y \Sexpr{REP$t_quito_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$t_quito_dem_2_f} años. El \Sexpr{REP$t_quito_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_transito_quito_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_transito_quito} se representa la pirámide poblacional de los Agentes de Tránsito de Quito.


{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Tránsito de Quito}
\label{tab:iess_transito_quito_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_quito_puestos.tex}
\end{longtable}
}
}

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Tránsito de Quito}
\label{tab:iess_transito_quito_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_quito_sexo.tex}
\end{longtable}
}
}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Tránsito de Quito}
\label{fig:iess_pir_transito_quito}
\includegraphics[scale=1]{graficos/iess_pir_transito_quito.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
{\bf Elaborado:} DAIE}
\end{figure}


El Cuerpo de Agentes de Tránsito de Quito se compone de \Sexpr{REP$t_quito_dem_4_1} agentes de Tránsito 1. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_transito_quito_puestos} se presenta más detalle de la distribución de puestos por sexo. El salario mensual promedio es USD \Sexpr{REP$t_quito_dem_5_1} para el Agente de Tránsito (ver la tabla \ref{tab:iess_metropolitanos_quito_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Tránsito de Quito}
\label{tab:iess_metropolitanos_quito_cargo_salario}
\scalebox{0.85}{
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_transito_quito_sal.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito  \\
{\bf Elaborado:} DAIE }
\end{table}

% \begin{figure}[H]
% \centering
% \captionsetup{justification=centering}
% \caption{Distribución por cargo del personal del Cuerpo de Agentes de Tránsito de Quito}
% \label{fig:iess_bar_transito_quito}
% \includegraphics[scale=0.8]{graficos/iess_bar_transito_quito.png}
% \caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
% {\bf Elaborado:} DAIE}
% \end{figure}

%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de Tránsito de Santo Domingo}
\label{chp_demog:transito_s_domingo}

El Cuerpo de Agentes de Tránsito de Santo Domingo consiste en \Sexpr{REP$t_s_domingo_dem_1} agentes, de los cuales \Sexpr{REP$t_s_domingo_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$t_s_domingo_dem_2_m} años; y \Sexpr{REP$t_s_domingo_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$t_s_domingo_dem_2_f} años. El \Sexpr{REP$t_s_domingo_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_transito_s_domingo_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_transito_s_domingo} se representa la pirámide poblacional de los Agentes de Tránsito de Santo Domingo.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Tránsito de Santo Domingo}
\label{fig:iess_pir_transito_s_domingo}
\includegraphics[scale=0.95]{graficos/iess_pir_transito_s_domingo.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE}
\end{figure}

{\setlength{\tabcolsep}{5pt}
{\fontsize{10}{11}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Tránsito de Santo Domingo}
\label{tab:iess_transito_s_domingo_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_s_domingo_puestos.tex}
\end{longtable}
}
}

El Cuerpo de Agentes de Tránsito de Santo Domingo se compone de \Sexpr{REP$t_s_domingo_dem_4_1} agentes de Tránsito 1. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_transito_s_domingo_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Tránsito de Santo Domingo}
\label{tab:iess_transito_s_domingo_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_s_domingo_sexo.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Tránsito de Santo Domingo}
\label{fig:iess_bar_transito_s_domingo}
\includegraphics[scale=0.8]{graficos/iess_bar_transito_s_domingo.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio es USD \Sexpr{REP$t_s_domingo_dem_5_1} para el Agente de Tránsito (ver la tabla \ref{tab:iess_metropolitanos_s_domingo_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Tránsito de Santo Domingo}
\label{tab:iess_metropolitanos_s_domingo_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_transito_s_domingo_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo  \\
{\bf Elaborado:} DAIE }
\end{table}


%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de Tránsito de Ambato}
\label{chp_demog:transito_ambato}

El Cuerpo de Agentes de Tránsito de Ambato consiste en \Sexpr{REP$t_ambato_dem_1} agentes, de los cuales \Sexpr{REP$t_ambato_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$t_ambato_dem_2_m} años; y \Sexpr{REP$t_ambato_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$t_ambato_dem_2_f} años. El \Sexpr{REP$t_ambato_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_transito_ambato_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_transito_ambato} se representa la pirámide poblacional de los Agentes de Tránsito de Ambato.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Tránsito de Ambato}
\label{fig:iess_pir_transito_ambato}
\includegraphics[scale=1]{graficos/iess_pir_transito_ambato.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato \\
{\bf Elaborado:} DAIE}
\end{figure}


{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Tránsito de Ambato}
\label{tab:iess_transito_ambato_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_ambato_sexo.tex}
\end{longtable}
}
}

El Cuerpo de Agentes de Tránsito de Ambato se compone de \Sexpr{REP$t_ambato_dem_4_1} agentes de Tránsito 1 y un (\Sexpr{REP$t_ambato_dem_4_2}) Jefe de tránsito y un (1) Gerente de Tránsito. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_transito_ambato_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Tránsito de Ambato}
\label{tab:iess_transito_ambato_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_ambato_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Tránsito de Ambato}
\label{fig:iess_bar_transito_ambato}
\includegraphics[scale=0.8]{graficos/iess_bar_transito_ambato.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio es USD \Sexpr{REP$t_ambato_dem_5_1} para el Agente de Tránsito, USD \Sexpr{REP$t_ambato_dem_5_2} para el Jefe de Tránsito y USD \Sexpr{REP$t_ambato_dem_5_3} para el Director de tránsito (ver la tabla \ref{tab:iess_metropolitanos_ambato_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Tránsito de Ambato}
\label{tab:iess_metropolitanos_ambato_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_transito_ambato_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato  \\
{\bf Elaborado:} DAIE }
\end{table}



%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de Tránsito de Riobamba}
\label{chp_demog:transito_riobamba}

El Cuerpo de Agentes de Tránsito de Riobamba consiste en \Sexpr{REP$t_riobamba_dem_1} agentes, de los cuales \Sexpr{REP$t_riobamba_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$t_riobamba_dem_2_m} años; y \Sexpr{REP$t_riobamba_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$t_riobamba_dem_2_f} años. El \Sexpr{REP$t_riobamba_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_transito_riobamba_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_transito_riobamba} se representa la pirámide poblacional de los Agentes de Tránsito de Riobamba.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Tránsito de Riobamba}
\label{fig:iess_pir_transito_riobamba}
\includegraphics[scale=1]{graficos/iess_pir_transito_riobamba.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Riobamba \\
{\bf Elaborado:} DAIE}
\end{figure}


{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Tránsito de Riobamba}
\label{tab:iess_transito_riobamba_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Riobamba \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_riobamba_sexo.tex}
\end{longtable}
}
}

El Cuerpo de Agentes de Tránsito de Riobamba se compone de \Sexpr{REP$t_riobamba_dem_4_1} agentes de Tránsito 1, un (\Sexpr{REP$t_riobamba_dem_4_2}) Director de Tránsito y un (1) Coordinador de tránsito. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_transito_riobamba_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Tránsito de Riobamba}
\label{tab:iess_transito_riobamba_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Riobamba \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_riobamba_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Tránsito de Riobamba}
\label{fig:iess_bar_transito_riobamba}
\includegraphics[scale=0.8]{graficos/iess_bar_transito_riobamba.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Riobamba \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio es USD \Sexpr{REP$t_riobamba_dem_5_1} para el Agente de Tránsito 1, USD \Sexpr{REP$t_riobamba_dem_5_2} para el Coordinador de tránsito y USD \Sexpr{REP$t_riobamba_dem_5_3} para el Director de Tránsito (ver la tabla \ref{tab:iess_metropolitanos_riobamba_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Tránsito de Riobamba}
\label{tab:iess_metropolitanos_riobamba_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_transito_riobamba_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Riobamba  \\
{\bf Elaborado:} DAIE }
\end{table}


%%--------------------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Agentes de Tránsito de Loja}
\label{chp_demog:transito_loja}

El Cuerpo de Agentes de Tránsito de Loja consiste en \Sexpr{REP$t_loja_dem_1} agentes, de los cuales \Sexpr{REP$t_loja_dem_1_m} son hombres, con una edad promedio igual a \Sexpr{REP$t_loja_dem_2_m} años; y \Sexpr{REP$t_loja_dem_1_f} mujeres, con edad promedio igual a \Sexpr{REP$t_loja_dem_2_f} años. El \Sexpr{REP$t_loja_dem_3}\% de los agentes se encuentran entre 20 y 30 años. En la tabla \ref{tab:iess_transito_loja_sexo} se presenta la distribución por rangos de edad y sexo; y en la figura \ref{fig:iess_pir_transito_loja} se representa la pirámide poblacional de los Agentes de Tránsito de Loja.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Agentes de Tránsito de Loja}
\label{fig:iess_pir_transito_loja}
\includegraphics[scale=1]{graficos/iess_pir_transito_loja.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Loja \\
{\bf Elaborado:} DAIE}
\end{figure}


{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{crrrrrr}
  \caption{Distribución por edad y sexo del Cuerpo de Agentes de Tránsito de Loja}
\label{tab:iess_transito_loja_sexo} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Loja \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_loja_sexo.tex}
\end{longtable}
}
}

El Cuerpo de Agentes de Tránsito de Loja se compone de \Sexpr{REP$t_loja_dem_4_1} agentes de Tránsito 1, \Sexpr{REP$t_loja_dem_4_2} Directores de Tránsito y un (1) Comisario de Tránsito. No se consideran puestos administrativos al no ser consideraros en el Código Orgánico de las Entidades de Seguridad Ciudadana y Orden Público. En la tabla \ref{tab:iess_transito_loja_puestos} se presenta más detalle de la distribución de puestos por sexo.

{\setlength{\tabcolsep}{5pt}
{\fontsize{11}{12}\selectfont
\begin{longtable}[H]{lrrrrrr}
  \caption{Distribución por cargo y sexo del personal del Cuerpo de Agentes de Tránsito de Loja}
\label{tab:iess_transito_loja_puestos} \\
\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
\midrule
\endfirsthead

\toprule
 \multicolumn{1}{l}{\multirow{2}{*}{Rango edad:}} & 
\multicolumn{2}{c}{Hombres} &
\multicolumn{2}{c}{Mujeres} &
\multicolumn{2}{c}{Total} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
& 
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} &
\multicolumn{1}{c}{Agentes} &
\multicolumn{1}{c}{Porcentaje (\%)} \\
	\midrule
\endhead

\bottomrule \multicolumn{7}{c}{continúa...} \\
\endfoot
%\hline
\caption*{\scriptsize {\bf Fuente:} Municipio de Loja \\
{\bf Elaborado:} DAIE }
\endlastfoot
  \input{tablas/iess_transito_loja_puestos.tex}
\end{longtable}
}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Agentes de Tránsito de Loja}
\label{fig:iess_bar_transito_loja}
\includegraphics[scale=0.8]{graficos/iess_bar_transito_loja.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Loja \\
{\bf Elaborado:} DAIE}
\end{figure}

El salario mensual promedio es USD \Sexpr{REP$t_loja_dem_5_1} para el Agente de Tránsito, USD \Sexpr{REP$t_loja_dem_5_2} para el Comisario de Tránsito y USD \Sexpr{REP$t_loja_dem_5_3} para el Director de Tránsito (ver la tabla \ref{tab:iess_metropolitanos_loja_cargo_salario}).

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Agentes de Tránsito de Loja}
\label{tab:iess_metropolitanos_loja_cargo_salario}
\begin{tabular}{lr}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_transito_loja_sal.tex}
\end{tabular}
\caption*{\scriptsize {\bf Fuente:} Municipio de Loja  \\
{\bf Elaborado:} DAIE }
\end{table}


% %---------------------------------------------------------------------------------------------------
\subsection{Cuerpos de Bomberos}
\label{chp_demog:bomberos}

%---------------------------------------------------------------------------------------------------
Para el presente estudio se considera el número de servidores públicos de los Cuerpos de Bomberos a marzo del 2022, que es de 3.935 servidores. Adicionalmente, para la realización de este análisis se tomaron en cuenta las ciudades: Quito, Ambato, Cuenca, Guayaquil, Loja, Machala, Portoviejo, Ibarra, Manta, Milagro, Riobamba y Santo Domingo. En la figura \ref{fig:iess_pir_bomberos} y tabla \ref{tab:iess_bomberos_edad_sexo} se muestra la distribución por edad y sexo de las y los servidores públicos de la mencionada entidad. En ellas se evidencia que, del total del personal de esta institución, el 21,30\% son mujeres y el 78,70\% son hombres. Además, el 39,47\% de los mismos tienen entre 30 y 40 años.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo de los Cuerpos de Bomberos}
\label{tab:iess_bomberos_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de cada ciudad \\
{\bf Elaborado:} DAIE}
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal de los Cuerpos de Bomberos}
\label{fig:iess_pir_bomberos}
\includegraphics[scale=0.9]{graficos/iess_pir_bomberos.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de cada ciudad \\
{\bf Elaborado:} DAIE}
\end{figure}

la figura \ref{fig:iess_bar_bomberos} detalla la distribución por cargo de las y los servidores públicos de los Cuerpos de Bomberos, mientras que En la tabla \ref{tab:iess_bomberos_cargo_sexo} se muestra la distribución por cargo y sexo de los mismos. En ambas se visualiza que el cargo que acumula a la mayoría de los servidores públicos de esta institución es \textit{Administrativo} con un total de 1.729 servidores, seguido por \textit{Bombero 1} con 1.840 servidores. Por otra parte, los cargos que concentran la menor cantidad de trabajadores son \textit{Subinspector de Estación} y \textit{Bombero 4}, con 10 y 8 servidores respectivamente. Además, en todos los cargos y en el total de hombres y mujeres se visibiliza una mayoría poblacional masculina.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal de los Cuerpos de Bomberos}
\label{fig:iess_bar_bomberos}
\includegraphics[scale=0.8]{graficos/iess_bar_bomberos.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de cada ciudad \\
{\bf Elaborado:} DAIE}
\end{figure}


\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal de los Cuerpos de Bomberos}
\label{tab:iess_bomberos_cargo_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_cargo_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de cada ciudad \\
{\bf Elaborado:} DAIE}
\end{table}


La tabla \ref{tab:iess_bomberos_cargo_salario} contempla el salario promedio de cada cargo de los Cuerpos de Bomberos ordenados de menor a mayor. En ella se observa que los salarios promedio de \textit{Bombero 3} y \textit{4} son superiores a los de \textit{Subinspector de Estación} e \textit{Inspector de Brigada}, lo cual es inconsistente con la jerarquía expuesta en el COESCOP.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de los Cuerpos de Bomberos}
\label{tab:iess_bomberos_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_bomberos_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de cada ciudad  \\
{\bf Elaborado:} DAIE}
\end{table}


A continuación, en la tabla \ref{tab:iess_bomberos_ciudad} se muestra la cantidad y porcentaje de hombres y mujeres que forman parte del Cuerpo de Bomberos de cada ciudad. Se observa que la ciudad que alberga la mayoría del personal de esta entidad es \textit{Quito}, con 1.600 servidores. Por otro lado, la ciudad con la menor cantidad de servidores de este ente es \textit{Milagro} con 109 de los mismos.

{\fontsize{11}{13}\selectfont
\begin{longtable}[H]{lrrrrrr}
\captionsetup{justification=centering}
\caption{Distribución por ciudad y sexo del personal del Cuerpo de Bomberos}
\label{tab:iess_bomberos_ciudad} \\
\toprule
Ciudad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\endfirsthead
\toprule
Ciudad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\endhead
\hline
\multicolumn{4}{r}{continúa...} \\
\endfoot
%\bottomrule
\caption*{\scriptsize {\bf Fuente:} Municipio de cada ciudad \\
{\bf Elaborado:} DAIE}
\endlastfoot
\input{tablas/iess_bomberos_ciudad.tex}
\end{longtable}
}


Seguidamente, se procede a realizar un análisis demográfico por ciudad.

%----------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Bomberos de Quito}
\label{chp_demog:bomberos_quito}

En la figura \ref{fig:iess_pir_bomberos_quito} y la tabla \ref{tab:iess_bomberos_quito_edad_sexo} se muestran la distribución por edad y sexo de las y los trabajadores de la presente entidad. A marzo del 2022 el total de servidores públicos pertenecientes al Cuerpo de Bomberos de Quito es de 1.378, de los cuales el 27,14\% son mujeres y el 72,86\% son hombres. También, del total del personal de esta entidad, el 34,91\% está entre loa 30 y 40 años.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Bomberos de Quito}
\label{fig:iess_pir_bomberos_quito}
\includegraphics[scale=0.8]{graficos/iess_pir_bomberos_quito.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
{\bf Elaborado:} DAIE}
\end{figure}

La figura \ref{fig:iess_bar_bomberos_quito} detalla la distribución por cargo de las y los servidores públicos del Cuerpo de Bomberos del Distrito Metropolitano de Quito, mientras que en la tabla \ref{tab:iess_bomberos_quito_cargo} se muestra la distribución por cargo y sexo de los mismos. En ellas se visualiza que \textit{Bombero 1} es el puesto que abarca una cantidad mayoritaria de servidores públicos de esta entidad, con un total de 639 servidores. Seguidamente se encuentra \textit{Administrativo} con 586 de los mismos. Por otro lado, \textit{Bombero 4} con menor cantidad de trabajadores con 1. Adicionalmente, los cargos \textit{Bombero 4} y \textit{Subjefe de Bomberos} no presentan trabajadores del género femenino.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Bomberos de Quito}
\label{fig:iess_bar_bomberos_quito}
\includegraphics[scale=0.8]{graficos/iess_bar_bomberos_quito.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del Cuerpo de Bomberos de Quito}
\label{tab:iess_bomberos_quito_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_quito_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
{\bf Elaborado:} DAIE}
\end{table}

\vspace{-0.5cm}
\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del Cuerpo de Bomberos de Quito}
\label{tab:iess_bomberos_quito_cargo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_quito_cargo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
{\bf Elaborado:} DAIE}
\end{table}

La tabla \ref{tab:iess_bomberos_quito_cargo_salario} detalla los salarios promedio de los cargos del Cuerpo de Bomberos de Quito ordenados de menor a mayor, en la cual se evidencia que el rango propuesto en el COESCOP es respetado a excepción de \textit{Subjefe de Bomberos}, que debería estar por debajo de \textit{Jefe de Bomberos}.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Bomberos de Quito}
\label{tab:iess_bomberos_quito_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_bomberos_quito_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Quito \\
{\bf Elaborado:} DAIE}
\end{table}


%----------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Bomberos de Ambato}
\label{chp_demog:bomberos_ambato}

La figura \ref{fig:iess_pir_bomberos_ambato} y tabla \ref{tab:iess_bomberos_ambato_edad_sexo} muestran la distribución por edad y sexo de las y los trabajadores de esta entidad. El total de miembros del Cuerpo de Bomberos de Ambato, a marzo del 2022, es de 179 servidores; donde el 13,41\% corresponde a trabajadores del género femenino y el 86,59\% al género masculino. Además, del total de los empleados, el 57,54\% tiene entre 30 y 40 años.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Bomberos de Ambato}
\label{fig:iess_pir_bomberos_ambato}
\includegraphics[scale=0.8]{graficos/iess_pir_bomberos_ambato.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del Cuerpo de Bomberos de Ambato}
\label{tab:iess_bomberos_ambato_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_ambato_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato \\
{\bf Elaborado:} DAIE}
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Bomberos de Ambato}
\label{fig:iess_bar_bomberos_ambato}
\includegraphics[scale=0.8]{graficos/iess_bar_bomberos_ambato.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato \\
{\bf Elaborado:} DAIE}
\end{figure}

La figura \ref{fig:iess_bar_bomberos_ambato} detalla la distribución por cargo de las y los servidores públicos del Cuerpo de Bomberos de Ambato, mientras que en la tabla \ref{tab:iess_bomberos_ambato_cargo} se muestra la distribución por cargo y sexo de los mismos. Ambas reflejan que el cargo que abarca una mayor cantidad de trabajadores es \textit{Bombero 1} con 133 servidores, seguido de \textit{Administrativo}, con 33. En cambio, los cargos con la menor cantidad de empleados son \textit{Jefe} y \textit{Subjefe de Bomberos}, con 2 servidor cada uno. Adicionalmente, \textit{Jefe de bomberos} y \textit{Subjefe de Bomberos} no cuentan con población femenina.

%\vspace{-0.5cm}
\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del Cuerpo de Bomberos de Ambato}
\label{tab:iess_bomberos_ambato_cargo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_ambato_cargo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato \\
{\bf Elaborado:} DAIE}
\end{table}

\vspace{-0.5cm}
La tabla \ref{tab:iess_bomberos_ambato_cargo_salario} contiene los salarios promedio de los cargos del Cuerpo de Bomberos de Ambato ordenados de menor a mayor. Se observa que la jerarquía impuesta en el COESCOP se mantiene.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Bomberos de Ambato}
\label{tab:iess_bomberos_ambato_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_bomberos_ambato_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ambato \\
{\bf Elaborado:} DAIE}
\end{table}

%----------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Bomberos de Cuenca}
\label{chp_demog:bomberos_cuenca}

En la figura \ref{fig:iess_pir_bomberos_cuenca} y la tabla \ref{tab:iess_bomberos_cuenca_edad_sexo} se muestran la distribución por edad y sexo de las y los trabajadores de la presente entidad. A marzo del 2022, el total de empleados del Cuerpo de Bomberos de Cuenca es de 191, del cual el 16,75\% son mujeres y el 83,25\% son hombres. Más aún, el 37,70\% del total del personal de la presente entidad se encuentra entre los 30 y 40 años.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del Cuerpo de Bomberos de Cuenca}
\label{tab:iess_bomberos_cuenca_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_cuenca_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Cuenca \\
{\bf Elaborado:} DAIE}
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Bomberos de Cuenca}
\label{fig:iess_pir_bomberos_cuenca}
\includegraphics[scale=0.9]{graficos/iess_pir_bomberos_cuenca.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Cuenca \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Bomberos de Cuenca}
\label{fig:iess_bar_bomberos_cuenca}
\includegraphics[scale=1]{graficos/iess_bar_bomberos_cuenca.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Cuenca \\
{\bf Elaborado:} DAIE}
\end{figure}

La figura \ref{fig:iess_bar_bomberos_cuenca} detalla la distribución por cargo de las y los servidores públicos del Cuerpo de Bomberos de Cuenca, mientras que en la tabla \ref{tab:iess_bomberos_cuenca_cargo} se muestra la distribución por cargo y sexo de los mismos. Ellas reflejan que el cargo con mayor cantidad de trabajadores de la presente entidad es \textit{Administrativo} con 114 servidores, seguido de \textit{Bombero 1} con 68. Por otro lado, \textit{Inspector de Brigada} y \textit{Jefe de Bomberos} son los puestos que acumulan la menor cantidad de empleados, con 2 y 7, respectivamente. Más aún, en los cargos \textit{Inspector de Brigada} y \textit{Jefe de Bomberos} no se encuentra población del género femenino.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del Cuerpo de Bomberos de Cuenca}
\label{tab:iess_bomberos_cuenca_cargo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_cuenca_cargo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Cuenca \\
{\bf Elaborado:} DAIE}
\end{table}

La tabla \ref{tab:iess_bomberos_cuenca_cargo_salario} hace referencia al salario promedio de cada uno de los cargos del Cuerpo de Bomberos de Cuenca ordenados de menor a mayor. Se evidencia que el rango explicitado en el COESCOP es respetado.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Bomberos de Cuenca}
\label{tab:iess_bomberos_cuenca_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_bomberos_cuenca_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Cuenca \\
{\bf Elaborado:} DAIE}
\end{table}

%----------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Bomberos de Guayaquil}
\label{chp_demog:bomberos_gye}

En la figura \ref{fig:iess_pir_bomberos_gye} y la tabla \ref{tab:iess_bomberos_gye_edad_sexo} se muestran la distribución por edad y sexo de las y los trabajadores de la presente entidad. El total de empleados del Cuerpo de Bomberos de Guayaquil, a marzo del 2022, es de 589 servidores, donde el 12,05\% corresponde a trabajadores del género femenino, mientras que el 87,95\% corresponde al género masculino. Además, del total del personal de esta institución, el 44,82\% tiene entre 30 y 40 años.


La figura \ref{fig:iess_bar_bomberos_gye} detalla la distribución por cargo de las y los servidores públicos del Cuerpo de Bomberos de Guayaquil, mientras que en la tabla \ref{tab:iess_bomberos_gye_cargo} se muestra la distribución por cargo y sexo de los mismos. En ambas se observa que \textit{Administrativo} es el cargo que alberga a la mayor cantidad de servidores públicos, con 406 de ellos. Seguidamente se encuentra \textit{Bombero 1}, con 158 de los mismos. También, \textit{Jefe de Bomberos} es el puesto con menos empleados de la presente entidad, con 6 servidores. Adicionalmente, en el cargo \textit{Inspector de Brigada} no existen empleados del género femenino. 

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del Cuerpo de Bomberos de Guayaquil}
\label{tab:iess_bomberos_gye_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_gye_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE}
\end{table}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Bomberos de Guayaquil}
\label{fig:iess_pir_bomberos_gye}
\includegraphics[scale=0.8]{graficos/iess_pir_bomberos_gye.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE}
\end{figure}


\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del Cuerpo de Bomberos de Guayaquil}
\label{tab:iess_bomberos_gye_cargo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_gye_cargo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE}
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Bomberos de Guayaquil}
\label{fig:iess_bar_bomberos_gye}
\includegraphics[scale=1]{graficos/iess_bar_bomberos_gye.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE}
\end{figure}

La tabla \ref{tab:iess_bomberos_gye_cargo_salario} detalla los salarios promedio de los cargos del Cuerpo de Bomberos de Guayaquil ordenados de menor a mayor, donde se observa que se cumple con la jerarquía establecida en el COESCOP.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Bomberos de Guayaquil}
\label{tab:iess_bomberos_gye_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_bomberos_gye_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Guayaquil \\
{\bf Elaborado:} DAIE}
\end{table}

%----------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Bomberos de Loja}
\label{chp_demog:bomberos_loja}

En la figura \ref{fig:iess_pir_bomberos_loja} y la tabla \ref{tab:iess_bomberos_loja_edad_sexo} se muestran la distribución por edad y sexo de las y los trabajadores de la presente entidad. A marzo del 2022, el total del personal del Cuerpo de Bomberos de Loja es de 108 empleados, de los cuales el 25,93\% son mujeres y el 74,07\% son hombres. Más aún, del total de empleados de esta entidad, el 45,37\% se encuentra entre los 30 y 40 años.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Bomberos de Loja}
\label{fig:iess_pir_bomberos_loja}
\includegraphics[scale=0.8]{graficos/iess_pir_bomberos_loja.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Loja \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del Cuerpo de Bomberos de Loja}
\label{tab:iess_bomberos_loja_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_loja_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Loja \\
{\bf Elaborado:} DAIE}
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Bomberos de Loja}
\label{fig:iess_bar_bomberos_loja}
\includegraphics[scale=0.8]{graficos/iess_bar_bomberos_loja.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Loja \\
{\bf Elaborado:} DAIE}
\end{figure}

La figura \ref{fig:iess_bar_bomberos_loja} detalla la distribución por cargo de las y los servidores públicos del Cuerpo de Bomberos de Loja, mientras que en la tabla \ref{tab:iess_bomberos_loja_cargo} se muestra la distribución por cargo y sexo de los mismos. Ambas reflejan que el cargo que contempla la mayor cantidad de empleados de esta entidad es \textit{Administrativo} con 29 servidores, seguido de \textit{Bombero 1} con 71. En cambio, los puestos con menor cantidad de trabajadores son \textit{Inspector de Brigada} y \textit{Jefe de Bomberos}, con 5 y 3, respectivamente.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del Cuerpo de Bomberos de Loja}
\label{tab:iess_bomberos_loja_cargo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_loja_cargo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Loja \\
{\bf Elaborado:} DAIE}
\end{table}

La tabla \ref{tab:iess_bomberos_loja_cargo_salario} contiene el salario promedio de cada cargo del Cuerpo de Bomberos de Loja ordenados de menor a mayor, donde observa que se mantiene el grado descrito en el COESCOP.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Bomberos de Loja}
\label{tab:iess_bomberos_loja_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_bomberos_loja_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Loja \\
{\bf Elaborado:} DAIE}
\end{table}

%----------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Bomberos de Machala}
\label{chp_demog:bomberos_machala}

En la figura \ref{fig:iess_pir_bomberos_machala} y la tabla \ref{tab:iess_bomberos_machala_edad_sexo} se muestran la distribución por edad y sexo de las y los trabajadores de la presente entidad. El total de servidores públicos del Cuerpo de Bomberos de Machala, a marzo del 2022, es de 113 empleados, de los cuales el 23,01\% son mujeres y el 76,99\% son hombres. Adicionalmente, el 37,17\% del total de servidores públicos que trabajan en esta entidad tienen entre 30 y 40 años.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Bomberos de Machala}
\label{fig:iess_pir_bomberos_machala}
\includegraphics[scale=0.8]{graficos/iess_pir_bomberos_machala.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del Cuerpo de Bomberos de Machala}
\label{tab:iess_bomberos_machala_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_machala_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE}
\end{table}

La figura \ref{fig:iess_bar_bomberos_machala} detalla la distribución por cargo de las y los servidores públicos del Cuerpo de Bomberos de Machala, mientras que en la tabla \ref{tab:iess_bomberos_machala_cargo} se muestra la distribución por cargo y sexo de los mismos. Éstas muestran que el cargo con mayor número de empleados de esta entidad es \textit{Bombero 1} con 74 servidores, seguido de \textit{Administrativo} con 26. Por su parte, \textit{Inspector de Brigada} es el cargo con menor cantidad de empleados, con 12 y \textit{Jefe de Bomberos} con 1.

{\fontsize{11}{13}\selectfont
\begin{longtable}[H]{lrrrrrr}
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del Cuerpo de Bomberos de Machala}
\label{tab:iess_bomberos_machala_cargo}\\
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\
\midrule
\endfirsthead
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\
\midrule
\endhead
\hline
\multicolumn{7}{r}{continúa...} \\
\endfoot
%\bottomrule
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE}
\endlastfoot
\input{tablas/iess_bomberos_machala_cargo.tex}
\end{longtable}
}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Bomberos de Machala}
\label{fig:iess_bar_bomberos_machala}
\includegraphics[scale=0.8]{graficos/iess_bar_bomberos_machala.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE}
\end{figure}


La tabla \ref{tab:iess_bomberos_machala_cargo_salario} refleja los salarios promedio de los cargos del Cuerpo de Bomberos de Machala, en ella se visualiza que los grados explicitados en el COESCOP se mantienen.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Bomberos de Machala}
\label{tab:iess_bomberos_machala_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_bomberos_machala_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Machala \\
{\bf Elaborado:} DAIE}
\end{table}

%----------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Bomberos de Portoviejo}
\label{chp_demog:bomberos_prtvj}

En la figura \ref{fig:iess_pir_bomberos_prtvj} y la tabla \ref{tab:iess_bomberos_prtvj_edad_sexo} se muestran la distribución por edad y sexo de las y los trabajadores de la presente entidad. A marzo del 2022, el total del personal del Cuerpo de Bomberos de Portoviejo es de 191 empleados, de donde el 18,85\% corresponde al personal femenino y el 81,15\% al personal masculino. Más aún, el 48,17\% del total del personal de la presente entidad tiene entre 30 y 40 años.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Bomberos de Portoviejo}
\label{fig:iess_pir_bomberos_prtvj}
\includegraphics[scale=0.8]{graficos/iess_pir_bomberos_prtvj.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Portoviejo \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del Cuerpo de Bomberos de Portoviejo}
\label{tab:iess_bomberos_prtvj_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_prtvj_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Portoviejo \\
{\bf Elaborado:} DAIE}
\end{table}

La figura \ref{fig:iess_bar_bomberos_prtvj} detalla la distribución por cargo de las y los servidores públicos del Cuerpo de Bomberos de Portoviejo, mientras que en la tabla \ref{tab:iess_bomberos_prtvj_cargo} se muestra la distribución por cargo y sexo de los mismos. En ellas se evidencia que \textit{Bombero 1} es el puesto con mayor cantidad de empleados con 80 de ellos, al tanto que \textit{Jefe de Bomberos} e \textit{Inspector de Brigada} son los puestos con menor cantidad de trabajadores con 2 y 6, respectivamente.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del Cuerpo de Bomberos de Portoviejo}
\label{tab:iess_bomberos_prtvj_cargo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_prtvj_cargo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Portoviejo \\
{\bf Elaborado:} DAIE}
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Bomberos de Portoviejo}
\label{fig:iess_bar_bomberos_prtvj}
\includegraphics[scale=1]{graficos/iess_bar_bomberos_prtvj.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Portoviejo \\
{\bf Elaborado:} DAIE}
\end{figure}

La tabla \ref{tab:iess_bomberos_prtvj_cargo_salario} contiene el salario promedio de cada cargo del Cuerpo de Bomberos de Portoviejo ordenados de menor a mayor; en ella se visualiza que no se siguen los grados descritos en el COESCOP.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Bomberos de Portoviejo}
\label{tab:iess_bomberos_prtvj_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_bomberos_prtvj_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Portoviejo \\
{\bf Elaborado:} DAIE}
\end{table}

%----------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Bomberos de Ibarra}
\label{chp_demog:bomberos_ibarra}

En la figura \ref{fig:iess_pir_bomberos_ibarra} y la tabla \ref{tab:iess_bomberos_ibarra_edad_sexo} se muestran la distribución por edad y sexo de las y los trabajadores de la presente entidad. El total de empleados del Cuerpo de Bomberos de Ibarra, a marzo del 2022, es de 152, de los cuales el 21,05\% son mujeres y el 78,95\% son hombres. También, del total de trabajadores de esta entidad, el 41,45\% se encuentra entre los 30 y 40 años.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Bomberos de Ibarra}
\label{fig:iess_pir_bomberos_ibarra}
\includegraphics[scale=0.8]{graficos/iess_pir_bomberos_ibarra.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ibarra \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del Cuerpo de Bomberos de Ibarra}
\label{tab:iess_bomberos_ibarra_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_ibarra_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ibarra \\
{\bf Elaborado:} DAIE}
\end{table}

La figura \ref{fig:iess_bar_bomberos_ibarra} detalla la distribución por cargo de las y los servidores públicos del Cuerpo de Bomberos de Ibarra, mientras que en la tabla \ref{tab:iess_bomberos_ibarra_cargo} se muestra la distribución por cargo y sexo de los mismos. En ambas se visualiza que \textit{Bombero 1} es el puesto con mayor cantidad de empleados, teniendo 126 servidores en este puesto. Seguidamente se encuentra \textit{Administrativos}, con 25 de los mismos. En cambio, los puestos con menos trabajadores de esta institución son \textit{Inspector de Brigada} con 1 servidor. Adicionalmente, el cargo \textit{Inspector de Brigada} no posee empleados del género femenino.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del Cuerpo de Bomberos de Ibarra}
\label{tab:iess_bomberos_ibarra_cargo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_ibarra_cargo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ibarra \\
{\bf Elaborado:} DAIE}
\end{table}

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Bomberos de Ibarra}
\label{fig:iess_bar_bomberos_ibarra}
\includegraphics[scale=1]{graficos/iess_bar_bomberos_ibarra.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ibarra \\
{\bf Elaborado:} DAIE}
\end{figure}

La tabla \ref{tab:iess_bomberos_ibarra_cargo_salario} refleja los salarios promedio por cargo del Cuerpo de Bomberos de Ibarra ordenados de menor a mayor, ésta muestra que el rango jerárquico detallado en el COESCOP es respetado.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Bomberos de Ibarra}
\label{tab:iess_bomberos_ibarra_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_bomberos_ibarra_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Ibarra \\
{\bf Elaborado:} DAIE}
\end{table}

%----------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Bomberos de Manta}
\label{chp_demog:bomberos_manta}

En la figura \ref{fig:iess_pir_bomberos_manta} y la tabla \ref{tab:iess_bomberos_manta_edad_sexo} se muestran la distribución por edad y sexo de las y los trabajadores de la presente entidad. El total de servidores públicos pertenecientes al Cuerpo de Bomberos de Manta, a marzo del 2022, es de 164; de los cuales el 12,20\% son mujeres y el 87,80\% son hombres. También, del total de empleados de esta entidad el 31,71\% corresponde a personas entre los 40 y 50 años.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Bomberos de Manta}
\label{fig:iess_pir_bomberos_manta}
\includegraphics[scale=1]{graficos/iess_pir_bomberos_manta.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Manta \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del Cuerpo de Bomberos de Manta}
\label{tab:iess_bomberos_manta_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_manta_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Manta \\
{\bf Elaborado:} DAIE}
\end{table}

La figura \ref{fig:iess_bar_bomberos_manta} detalla la distribución por cargo de las y los servidores públicos del Cuerpo de Bomberos de Manta, mientras que en la tabla \ref{tab:iess_bomberos_manta_cargo} se muestra la distribución por cargo y sexo de los mismos. Ambas reflejan que \textit{Administrativo} es el cargo que acumula una cantidad de trabajadores superior al resto de puestos, con 91 servidores públicos. Seguidamente se encuentra \textit{Bombero 1}, con 43 de los mismos. Por el contrario, el cargo con menor cantidad de empleados es \textit{Jefe de Bomberos}, con 19 servidores en este puesto. Además, el cargo \textit{Inspector de Brigada} carece de personal del género femenino.

{\fontsize{11}{13}\selectfont
\begin{longtable}[H]{lrrrrrr}
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del Cuerpo de Bomberos de Manta}
\label{tab:iess_bomberos_manta_cargo} \\
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\
\midrule
\endfirsthead
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\
\midrule
\endhead
\hline
\multicolumn{7}{r}{continúa...} \\
\endfoot
%\bottomrule
\caption*{\scriptsize {\bf Fuente:} Municipio de Manta \\
{\bf Elaborado:} DAIE}
\endlastfoot
\input{tablas/iess_bomberos_manta_cargo.tex}
\end{longtable}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Bomberos de Manta}
\label{fig:iess_bar_bomberos_manta}
\includegraphics[scale=0.8]{graficos/iess_bar_bomberos_manta.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Manta \\
{\bf Elaborado:} DAIE}
\end{figure}

La tabla \ref{tab:iess_bomberos_manta_cargo_salario} muestra el salario promedio de cada uno de los cargos del Cuerpo de Bomberos de Manta ordenados de menor a mayor. Se visibiliza que se mantiene la jerarquía expuesta en el COESCOP.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Bomberos de Manta}
\label{tab:iess_bomberos_manta_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_bomberos_manta_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Manta \\
{\bf Elaborado:} DAIE}
\end{table}

%----------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Bomberos de Milagro}
\label{chp_demog:bomberos_milagro}

En la figura \ref{fig:iess_pir_bomberos_milagro} y la tabla \ref{tab:iess_bomberos_milagro_edad_sexo} se muestran la distribución por edad y sexo de las y los trabajadores de la presente entidad. A marzo del 2022, el total de empleados del Cuerpo de Bomberos de Milagro es de 94, de donde el 20,21\% son mujeres y el 79,79\% son hombres. Más aún, del total del personal, el 36,17\% se encuentra entre los 40 y 50 años.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Bomberos de Milagro}
\label{fig:iess_pir_bomberos_milagro}
\includegraphics[scale=1]{graficos/iess_pir_bomberos_milagro.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Milagro \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del Cuerpo de Bomberos de Milagro}
\label{tab:iess_bomberos_milagro_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_milagro_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Milagro \\
{\bf Elaborado:} DAIE}
\end{table}

La figura \ref{fig:iess_bar_bomberos_milagro} detalla la distribución por cargo de las y los servidores públicos del Cuerpo de Bomberos de Milagro, mientras que en la tabla \ref{tab:iess_bomberos_milagro_cargo} se muestra la distribución por cargo y sexo de los mismos. En éstas se visualiza que el puesto que contempla una mayor cantidad de servidores públicos es \textit{Bombero 1} con 64 empleados, seguido de \textit{Administrativo} con 22 de los mismos. En cambio, los cargos con menos empleados son \textit{Jefe de Bomberos} y \textit{Subjefe de Bomberos} con 3 y 5 servidores respectivamente. También, se observa que en los cargos \textit{Jefe} y \textit{Subjefe de Bomberos} no existen trabajadores del género femenino.

{\fontsize{11}{13}\selectfont
\begin{longtable}[H]{lrrrrrr}
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del Cuerpo de Bomberos de Milagro}
\label{tab:iess_bomberos_milagro_cargo} \\
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\   
\midrule
\endfirsthead
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\endhead
\hline
\multicolumn{7}{r}{continúa...} \\
\endfoot
%\bottomrule
\caption*{\scriptsize {\bf Fuente:} Municipio de Milagro \\
{\bf Elaborado:} DAIE}
\endlastfoot
\input{tablas/iess_bomberos_milagro_cargo.tex}
\end{longtable}
}


\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Bomberos de Milagro}
\label{fig:iess_bar_bomberos_milagro}
\includegraphics[scale=0.8]{graficos/iess_bar_bomberos_milagro.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Milagro \\
{\bf Elaborado:} DAIE}
\end{figure}

La tabla \ref{tab:iess_bomberos_milagro_cargo_salario} detalla los salarios promedio de los cargos del Cuerpo de Bomberos de Milagro ordenados de menor a mayor, donde se muestra que el rango expuesto en el COESCOP es respetado.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Bomberos de Milagro}
\label{tab:iess_bomberos_milagro_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_bomberos_milagro_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Milagro  \\
{\bf Elaborado:} DAIE}
\end{table}

%----------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Bomberos de Riobamba}
\label{chp_demog:bomberos_riobamba}

En la figura \ref{fig:iess_pir_bomberos_riobamba} y la tabla \ref{tab:iess_bomberos_riobamba_edad_sexo} se muestran la distribución por edad y sexo de las y los trabajadores de la presente entidad. El total del personal del Cuerpo de Bomberos de Riobamba, a marzo del 2022, es de 96 servidores públicos, de los cuales el 23,96\% son mujeres y el 76,04\% son hombres. Adicionalmente, del total de empleados de esta institución, el 50\% tiene entre 30 y 40 años.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Bomberos de Riobamba}
\label{fig:iess_pir_bomberos_riobamba}
\includegraphics[scale=1]{graficos/iess_pir_bomberos_riobamba.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Riobamba \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del Cuerpo de Bomberos de Riobamba}
\label{tab:iess_bomberos_riobamba_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_riobamba_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Riobamba \\
{\bf Elaborado:} DAIE}
\end{table}

La figura \ref{fig:iess_bar_bomberos_riobamba} detalla la distribución por cargo de las y los servidores públicos del Cuerpo de Bomberos de Riobamba, mientras que en la tabla \ref{tab:iess_bomberos_riobamba_cargo} se muestra la distribución por cargo y sexo de los mismos. Éstas reflejan que los puestos que abarcan la mayoría del personal de este ente son \textit{Administrativo} con 40 empleados y \textit{Bombero 1} con 35, en tanto que \textit{Jefe de Bomberos} y \textit{Subinspector de Estación} son los puestos con menor cantidad de trabajadores, 1 cada uno. Más aún, los cargos \textit{Bombero 1,3, Jefe de Bomberos} y \textit{Subinspector de Estación} carecen de personal del género femenino.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Bomberos de Riobamba}
\label{fig:iess_bar_bomberos_riobamba}
\includegraphics[scale=0.8]{graficos/iess_bar_bomberos_riobamba.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Riobamba \\
{\bf Elaborado:} DAIE}
\end{figure}

\vspace{-0.5cm}
\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del Cuerpo de Bomberos de Riobamba}
\label{tab:iess_bomberos_riobamba_cargo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_riobamba_cargo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Riobamba \\
{\bf Elaborado:} DAIE}
\end{table}

La tabla \ref{tab:iess_bomberos_riobamba_cargo_salario} contiene el salario promedio de cada cargo del Cuerpo de Bomberos de Riobamba ordenados de menor a mayor, en ella se muestra que a excepción de \textit{Inspector de Brigada} que debería estar por encima de \textit{Subinspector de Estación}, los salarios promedio se encuentran acorde a la jerarquía dictada en el COESCOP.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Bomberos de Riobamba}
\label{tab:iess_bomberos_riobamba_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_bomberos_riobamba_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Riobamba \\
{\bf Elaborado:} DAIE}
\end{table}

%----------------------------------------------------------------------------------------
\subsubsection{Cuerpo de Bomberos de Santo Domingo}
\label{chp_demog:bomberos_sto_dom}

En la figura \ref{fig:iess_pir_bomberos_sto_dom} y la tabla \ref{tab:iess_bomberos_sto_dom_edad_sexo} se muestran la distribución por edad y sexo de las y los trabajadores de la presente entidad. A marzo del 2022, el total de trabajadores del Cuerpo de Bomberos de Santo Domingo es de 146, de los cuales el 25,34\% son mujeres y el 74,66\% son hombres. Más aún, del total del personal, el 49,32\% tiene entre 20 y 30 años.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del personal del Cuerpo de Bomberos de Santo Domingo}
\label{fig:iess_pir_bomberos_sto_dom}
\includegraphics[scale=0.8]{graficos/iess_pir_bomberos_sto_dom.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por edad y sexo del Cuerpo de Bomberos de Santo Domingo}
\label{tab:iess_bomberos_sto_dom_edad_sexo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Rango Edad & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_sto_dom_edad_sexo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE}
\end{table}

La figura \ref{fig:iess_bar_bomberos_sto_dom} detalla la distribución por cargo de las y los servidores públicos del Cuerpo de Bomberos de Santo Domingo, mientras que en la tabla \ref{tab:iess_bomberos_sto_dom_cargo} se muestra la distribución por cargo y sexo de los mismos. Ambas muestran que los cargos que abarcan la mayor cantidad de empleados de esta institución son \textit{Administrativo} y \textit{Bombero 1} con 45 y 94 servidores respectivamente, mientras que los cargos con menos empleados son \textit{Jefe de Bomberos} con 1. También, en los cargos \textit{Inspector de Brigada} y \textit{Jefe de Bomberos} no existe personal del género femenino.

\begin{figure}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo del personal del Cuerpo de Bomberos de Santo Domingo}
\label{fig:iess_bar_bomberos_sto_dom}
\includegraphics[scale=0.8]{graficos/iess_bar_bomberos_sto_dom.png}
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE}
\end{figure}

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Distribución por cargo y sexo del personal del Cuerpo de Bomberos de Santo Domingo}
\label{tab:iess_bomberos_sto_dom_cargo}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Hombres & Hombres (\%) & Mujeres  & Mujeres (\%) & Total & Total (\%)\\  
\midrule
\input{tablas/iess_bomberos_sto_dom_cargo.tex}
 
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE}
\end{table}

La tabla \ref{tab:iess_bomberos_sto_dom_cargo_salario} detalla los salarios promedio de los cargos del Cuerpo de Bomberos de Santo Domingo ordenados de menor a menor, en ella se muestra que los grados jerárquicos expuestos en el COESCOP se mantienen.

\begin{table}[H]
\centering
\captionsetup{justification=centering}
\caption{Salario promedio por cargo del personal del Cuerpo de Bomberos de Santo Domingo}
\label{tab:iess_bomberos_sto_dom_cargo_salario}
\scalebox{0.8}{
\begin{tabular}{*{7}{r}}
\toprule
Cargo COESCOP & Salario Promedio\\  
\midrule
\input{tablas/iess_bomberos_sto_dom_cargo_salario.tex}
\end{tabular}
}
\caption*{\scriptsize {\bf Fuente:} Municipio de Santo Domingo \\
{\bf Elaborado:} DAIE}
\end{table}